stages:
- runall
- build
- collate

# This is just a config to help trigger rest of the builds
run_all_builds:
  image: ubuntu:latest
  stage: runall
  variables:
    GIT_STRATEGY: none
  script:
  - pwd
  when: manual
  allow_failure: false

# Build
build_osx_runtime:
  stage: build
  tags:
    - buildfarm
    - darwin
  when: manual
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - chmod +x external/buildscripts/bee
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - perl external/buildscripts/build_runtime_osx.pl
  - mkdir -p incomingbuilds/osx-i386
  - cp -r builds/ incomingbuilds/osx-i386/
  artifacts:
    paths:
    - incomingbuilds/osx-i386
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_osx_classlibs:
  stage: build
  tags:
    - buildfarm
    - darwin
  when: manual
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - chmod +x external/buildscripts/bee
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - perl external/buildscripts/build_classlibs_osx.pl
  - mkdir -p incomingbuilds/classlibs
  - cp -r ZippedClasslibs.tar.gz incomingbuilds/classlibs/
  artifacts:
    paths:
    - incomingbuilds/classlibs
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_android:
  stage: build
  tags:
    - buildfarm
    - darwin
  when: manual
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - chmod +x external/buildscripts/bee
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - bash external/buildscripts/build_runtime_android.sh
  - mkdir -p incomingbuilds/android/
  - cp -r builds/ incomingbuilds/android/
  artifacts:
    paths:
    - incomingbuilds/android
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_win:
  stage: build
  tags:
  - buildfarm
  - windows
  when: manual
  script:
  - git submodule update --init --recursive
  - cd external/buildscripts
  - ./bee.exe
  - cd ../..
  - perl external/buildscripts/build_runtime_win64.pl
  - mkdir -p incomingbuilds/win64
  - cp -r builds/* incomingbuilds/win64/
  artifacts:
    paths:
    - incomingbuilds/win64
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build_win_x86:
  stage: build
  tags:
  - buildfarm
  - windows
  when: manual
  script:
  - git submodule update --init --recursive
  - cd external/buildscripts
  - ./bee.exe
  - cd ../..
  - perl external/buildscripts/build_runtime_win.pl
  - mkdir -p incomingbuilds/win32
  - cp -r builds/* incomingbuilds/win32/
  artifacts:
    paths:
    - incomingbuilds/win32
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build_win_bare_minimum:
  stage: build
  tags:
  - buildfarm
  - windows
  when: manual
  script:
  - git submodule update --init --recursive
  - cd external/buildscripts
  - ./bee.exe
  - cd ../..
  - perl external/buildscripts/build_unityscript_bareminimum_win.pl
  - mkdir -p incomingbuilds/bareminimum
  - cp -r builds/* incomingbuilds/bareminimum/
  artifacts:
    paths:
    - incomingbuilds/bareminimum
    expire_in: 1 week
# Important! Do not remove this after_script!!
  after_script:
    - C:\Users\builduser\post_build_script.bat

build_linux_x64:
  stage: build
  tags:
  - buildfarm
  - linux
  when: manual
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - chmod +x external/buildscripts/bee
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - perl external/buildscripts/build_runtime_linux.pl -build64=1
  - mkdir incomingbuilds/linux64
  - cp -r builds/ incomingbuilds/linux64/
  artifacts:
    paths:
    - incomingbuilds/linux64
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

build_linux_x86:
  stage: build
  tags:
  - buildfarm
  - linux
  when: manual
  script:
  - git submodule update --init --recursive
  - echo -e "[auth]\nono.schemes=https\nono.prefix=ono.unity3d.com\nono.username=$GITLAB_UNITY_META_ONO_USER\nono.password=$GITLAB_UNITY_META_ONO_PASS\n" >> ~/.hgrc
  - chmod +x external/buildscripts/bee
  - cd external/buildscripts
  - ./bee
  - cd ../..
  - perl external/buildscripts/build_runtime_linux.pl
  - mkdir -p incomingbuilds/linux32
  - cp -r builds/ incomingbuilds/linux32/
  artifacts:
    paths:
    - incomingbuilds/linux32
    expire_in: 1 week
# Important! Do not remove this after_script!!  
  after_script:
    - /opt/post_build_script.sh

collate_builds:
  image: ubuntu:latest
  stage: collate
  when: manual
  dependencies:
  - build_osx_runtime
  - build_osx_classlibs
  - build_win
  - build_win_x86
  - build_win_bare_minimum
  - build_linux_x86
  - build_linux_x64
  before_script:
  - apt-get update -qy && apt-get -qy upgrade
  - apt-get install -qy perl
  - apt-get install -qy zip unzip
  script:
  - perl external/buildscripts/collect_allbuilds.pl